name: driver_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.0.0
  provider: ^5.0.0
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.3
  firebase_storage: ^8.0.5
  firebase_database: ^6.1.2
  firebase_analytics: ^8.0.3
  dartz: ^0.9.2
  logger: ^1.0.0
  get_it: ^7.1.2
  string_validator: ^0.3.0
  another_flushbar: ^1.10.20
  lottie: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/raw/